pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                git url: 'https://github.com/yohuang/TestProjects.git'
            }
        }
        stage('build') {
            steps {
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml clean"
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml compile"
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml jar"
            }
        }
        stage('docker') {
            steps {
                sh "docker-compose -f HelloWorld/docker-compose.yml build"
            }
        }
        stage('test') {
            steps {
                sh "docker-compose -f HelloWorld/docker-compose.yml up -d"
            }
        }
    }
    post {
        always {
            sh "docker-compose -f HelloWorld/docker-compose.yml down"
        }
    }
}

