pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                git url: 'https://github.com/yohuang/TestProjects.git'
            }
        }
        stage('build') {
            steps {
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml clean"
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml compile"
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml jar"
            }
        }
        stage('docker') {
            steps {
                sh "docker image build -t helloworld HelloWorld"
                sh "docker tag helloworld lenovo:5000/helloworld"
                sh "docker push lenovo:5000/helloworld"
            }
        }
        stage('staging test') {
            steps {
                sh "docker container run --rm lenovo:5000/helloworld"
            }
        }
    }
}

