pipeline {
    agent {
        docker {
            image 'openjdk:8-jdk-alpine'
        }
    }
    stages {
        stage('checkout') {
            steps {
                git url: 'https://github.com/yohuang/TestProjects.git'
            }
        }
        stage('build') {
            steps {
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml clean"
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml compile"
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml jar"
            }
        }
        stage('test') {
            steps {
                sh "apache-ant-1.10.6/bin/ant -f HelloWorld/build.xml run"
            }
        }
    }
}

